#!/usr/bin/env python
# -*- coding: CP949 -*-
#
# generated by wxGlade 0.7.0 on Wed Aug 26 15:54:47 2015
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.MDIChildFrame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        wx.MDIChildFrame.__init__(self, *args, **kwds)
        self.button_nC = wx.Button(self, wx.ID_ANY, _("Name Changer"))
        self.button_fastboot = wx.Button(self, wx.ID_ANY, _("FastBoot"))
        self.button_3 = wx.Button(self, wx.ID_ANY, _("TBD"))
        self.button_4 = wx.Button(self, wx.ID_ANY, _("TBD"))
        self.button_5 = wx.Button(self, wx.ID_ANY, _("TBD"))
        self.button_6 = wx.Button(self, wx.ID_ANY, _("TBD"))
        self.button_7 = wx.Button(self, wx.ID_ANY, _("TBD"))
        self.button_8 = wx.Button(self, wx.ID_ANY, _("TBD"))
        self.button_9 = wx.Button(self, wx.ID_ANY, _("TBD"))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.onNameChanger, self.button_nC)
        self.Bind(wx.EVT_BUTTON, self.onFastBoot, self.button_fastboot)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle(_("suker AllRound"))
        self.SetBackgroundColour(wx.Colour(255, 255, 0))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_main = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_main = wx.GridSizer(3, 3, 2, 2)
        grid_sizer_main.Add(self.button_nC, 0, wx.ALL | wx.EXPAND, 3)
        grid_sizer_main.Add(self.button_fastboot, 0, wx.ALL | wx.EXPAND, 3)
        grid_sizer_main.Add(self.button_3, 0, wx.ALL, 3)
        grid_sizer_main.Add(self.button_4, 0, wx.ALL, 3)
        grid_sizer_main.Add(self.button_5, 0, wx.ALL, 3)
        grid_sizer_main.Add(self.button_6, 0, wx.ALL, 3)
        grid_sizer_main.Add(self.button_7, 0, wx.ALL, 3)
        grid_sizer_main.Add(self.button_8, 0, wx.ALL, 3)
        grid_sizer_main.Add(self.button_9, 0, wx.ALL, 3)
        sizer_main.Add(grid_sizer_main, 1, wx.ALL | wx.EXPAND, 0)
        self.SetSizer(sizer_main)
        sizer_main.Fit(self)
        self.Layout()
        # end wxGlade

    def onNameChanger(self, event):  # wxGlade: MyFrame.<event_handler>
        print "Event handler 'onNameChanger' not implemented!"
        event.Skip()

    def onFastBoot(self, event):  # wxGlade: MyFrame.<event_handler>
        print "Event handler 'onFastBoot' not implemented!"
        event.Skip()

# end of class MyFrame
