#!/usr/bin/env python
# -*- coding: CP949 -*-
#
# generated by wxGlade 0.7.0 on Thu Aug 13 10:44:30 2015
#

import wx

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.MDIChildFrame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        wx.MDIChildFrame.__init__(self, *args, **kwds)
        self.button_1 = wx.Button(self, wx.ID_ANY, _("button_1"))
        self.button_2 = wx.Button(self, wx.ID_ANY, _("button_2"))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.onDo1, self.button_1)
        self.Bind(wx.EVT_BUTTON, self.onDo2, self.button_2)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle(_("frame_1"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_3.Add(self.button_1, 0, wx.ALL | wx.EXPAND, 0)
        sizer_3.Add(self.button_2, 0, wx.ALL | wx.EXPAND, 0)
        sizer_2.Add(sizer_3, 1, 0, 0)
        sizer_1.Add(sizer_2, 1, 0, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def onDo1(self, event):  # wxGlade: MyFrame.<event_handler>
        print "Event handler 'onDo1' not implemented!"
        event.Skip()

    def onDo2(self, event):  # wxGlade: MyFrame.<event_handler>
        print "Event handler 'onDo2' not implemented!"
        event.Skip()

# end of class MyFrame
