#!/usr/bin/env python
# -*- coding: CP949 -*-
#
# generated by wxGlade 0.7.0 on Tue Aug 11 09:50:36 2015
#

import wx
import os

# begin wxGlade: dependencies
#import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class nameChanger(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame2.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.label_9 = wx.StaticText(self, wx.ID_ANY, _("Target Path"))
        self.text_ctrl_path = wx.TextCtrl(self, wx.ID_ANY, "")
        self.button_path = wx.Button(self, wx.ID_ANY, _("..."))
        self.label_10 = wx.StaticText(self, wx.ID_ANY, _("before"))
        self.text_ctrl_before = wx.TextCtrl(self, wx.ID_ANY, "")
        self.label_13 = wx.StaticText(self, wx.ID_ANY, "")
        self.label_14 = wx.StaticText(self, wx.ID_ANY, "")
        self.label_16 = wx.StaticText(self, wx.ID_ANY, _("after"))
        self.text_ctrl_after = wx.TextCtrl(self, wx.ID_ANY, "")
        self.label_15 = wx.StaticText(self, wx.ID_ANY, "")
        self.button_run = wx.Button(self, wx.ID_ANY, _("Run"))
        self.label_12 = wx.StaticText(self, wx.ID_ANY, _("Created by Suker version 0.1   since 2015.08.08"))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.setTargetPath, self.button_path)
        self.Bind(wx.EVT_BUTTON, self.Run, self.button_run)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame2.__set_properties
        self.SetTitle(_("Suker Name changer"))
        _icon = wx.EmptyIcon()
        _icon.CopyFromBitmap(wx.Bitmap("D:\\7_Project_My\\08_PythonProject\\layouts\\404.ico", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        self.SetBackgroundColour(wx.Colour(11, 99, 3))
        self.label_9.SetForegroundColour(wx.Colour(255, 255, 255))
        self.label_10.SetForegroundColour(wx.Colour(255, 255, 255))
        self.label_16.SetForegroundColour(wx.Colour(255, 255, 255))
        self.label_12.SetForegroundColour(wx.Colour(255, 255, 255))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame2.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.GridSizer(5, 1, 0, 0)
        grid_sizer_4 = wx.GridSizer(1, 4, 0, 0)
        grid_sizer_3 = wx.GridSizer(1, 4, 0, 0)
        grid_sizer_2 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_1.Add(self.label_9, 10, wx.ALIGN_BOTTOM | wx.ALL, 0)
        grid_sizer_2.Add(self.text_ctrl_path, 80, wx.ALL | wx.EXPAND, 0)
        grid_sizer_2.Add(self.button_path, 20, wx.ALIGN_RIGHT | wx.ALL, 0)
        grid_sizer_1.Add(grid_sizer_2, 20, wx.ALL | wx.EXPAND, 3)
        grid_sizer_3.Add(self.label_10, 20, wx.ALL | wx.EXPAND, 1)
        grid_sizer_3.Add(self.text_ctrl_before, 30, wx.ALL | wx.EXPAND, 0)
        grid_sizer_3.Add(self.label_13, 10, wx.ALL | wx.EXPAND, 0)
        grid_sizer_3.Add(self.label_14, 30, wx.ALL | wx.EXPAND, 0)
        grid_sizer_1.Add(grid_sizer_3, 20, wx.ALL | wx.EXPAND, 3)
        grid_sizer_4.Add(self.label_16, 20, wx.ALL | wx.EXPAND, 0)
        grid_sizer_4.Add(self.text_ctrl_after, 30, wx.ALL | wx.EXPAND, 0)
        grid_sizer_4.Add(self.label_15, 10, wx.ALL | wx.EXPAND, 0)
        grid_sizer_4.Add(self.button_run, 30, wx.ALL | wx.EXPAND, 0)
        grid_sizer_1.Add(grid_sizer_4, 20, wx.ALL | wx.EXPAND, 3)
        grid_sizer_1.Add(self.label_12, 10, wx.ALIGN_CENTER_VERTICAL | wx.ALIGN_RIGHT | wx.ALL, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.ALL | wx.EXPAND, 1)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def setTargetPath(self, event):  # wxGlade: MyFrame2.<event_handler>        
        dlg = wx.DirDialog(self, "Choose a directory:", style=wx.DD_DEFAULT_STYLE | wx.DD_NEW_DIR_BUTTON)
        #dlg.SetPath(self.text_ctrl_path.GetValue())
        
        if dlg.ShowModal() == wx.ID_OK:
            newPath = dlg.GetPath()
            self.text_ctrl_path.SetValue(newPath)
            
        dlg.Destroy()
        event.Skip()

    def Run(self, event):  # wxGlade: MyFrame2.<event_handler>
        before = self.text_ctrl_before.GetValue()
        after = self.text_ctrl_after.GetValue()
        
        os.chdir(self.text_ctrl_path.GetValue())
        for root, dirs, files in os.walk('./'):
            for dirr in dirs:
                temp = dirr.decode('cp949')
                if before in temp:
                    changedName = dirr.replace(before.encode('cp949'),after)
                    os.rename(temp,changedName)
                    
        event.Skip()

# end of class MyFrame2
