function build_uboot()
{
	if [ ${BUILD_ALL} == "true" ] || [ ${BUILD_UBOOT} == "true" ]; then
		echo ""
		echo "================================================="
		echo "build u-boot"
		echo "================================================="

		cd ${S}

		local config=
		if [ ${BOARD_NAME} == ${BOARD_PURENAME} ]; then
			config=s5p6818_arm64_${BOARD_NAME}
		else
			config=${BOARD_NAME}
		fi

		make clean
		make ${config}_config

		cross_compile=$(get_cross_compile_prefix)-
		if [ "${RELEASE_VERSION}" != "" ]; then
			make CROSS_COMPILE=${cross_compile} EXTRAVERSION="-$RELEASE_VERSION" -j8
		else
			make CROSS_COMPILE=${cross_compile} -j8
		fi

		build_uboot_env_param ${cross_compile}

		PLAIN_VERSION=`cat include/generated/version_autogenerated.h | grep "define PLAIN_VERSION" | awk -F \" '{print $2}'`
		UBOOT_VERSION="U-Boot $PLAIN_VERSION"
		cd ${TOP}

		if [ "${ARM_ARCH}" == "arm64" ]; then
			local uart_base=
			if [ ${BOARD_NAME} == ${BOARD_PURENAME} ]; then
				# ex> drone : use uart0
				uart_base=0xc00a1000
			else
				# ex> artik710_raptor : use uart3
				uart_base=0xc00a3000
			fi

			if [ ${BUILD_UBOOT} == "true" ]; then
				make -f optee_build/Makefile PLAT_DRAM_SIZE=${MEM_SIZE} PLAT_UART_BASE=${uart_base} build-fip -j8
				make -f optee_build/Makefile PLAT_DRAM_SIZE=${MEM_SIZE} PLAT_UART_BASE=${uart_base} build-singleimage -j8
			fi
		fi
	fi
}

