# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from stockInfo import stockInfoCls

MAX_LENGTH = 7

class Ui_MainWindow(object):
    infoCls = ""
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(773, 610)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 751, 521))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 731, 41))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 6, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 5, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_35.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_35.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_35.setText("")
        self.label_35.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_35.setIndent(-1)
        self.label_35.setObjectName("label_35")
        self.gridLayout.addWidget(self.label_35, 0, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 3)
        self.gridLayout.setColumnStretch(2, 3)
        self.gridLayout.setColumnStretch(3, 3)
        self.gridLayout.setColumnStretch(4, 3)
        self.gridLayout.setColumnStretch(5, 3)
        self.gridLayout.setColumnStretch(6, 3)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 60, 731, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_3 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_3.sizePolicy().hasHeightForWidth())
        self.checkBox_3.setSizePolicy(sizePolicy)
        self.checkBox_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_3.setText("")
        self.checkBox_3.setChecked(False)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout.addWidget(self.checkBox_3)
        self.label_J1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_J1.setFont(font)
        self.label_J1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_J1.setObjectName("label_J1")
        self.horizontalLayout.addWidget(self.label_J1)
        self.label_currentPrice1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_currentPrice1.setFont(font)
        self.label_currentPrice1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_currentPrice1.setObjectName("label_currentPrice1")
        self.horizontalLayout.addWidget(self.label_currentPrice1)
        self.label_buyPrice1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_buyPrice1.setFont(font)
        self.label_buyPrice1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_buyPrice1.setObjectName("label_buyPrice1")
        self.horizontalLayout.addWidget(self.label_buyPrice1)
        self.label_amount1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_amount1.setFont(font)
        self.label_amount1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_amount1.setObjectName("label_amount1")
        self.horizontalLayout.addWidget(self.label_amount1)
        self.label_today1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_today1.setFont(font)
        self.label_today1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_today1.setObjectName("label_today1")
        self.horizontalLayout.addWidget(self.label_today1)
        self.label_profit1 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_profit1.setFont(font)
        self.label_profit1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_profit1.setObjectName("label_profit1")
        self.horizontalLayout.addWidget(self.label_profit1)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 3)
        self.horizontalLayout.setStretch(2, 3)
        self.horizontalLayout.setStretch(3, 3)
        self.horizontalLayout.setStretch(4, 3)
        self.horizontalLayout.setStretch(5, 3)
        self.horizontalLayout.setStretch(6, 3)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 100, 731, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_4.sizePolicy().hasHeightForWidth())
        self.checkBox_4.setSizePolicy(sizePolicy)
        self.checkBox_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_4.setText("")
        self.checkBox_4.setChecked(False)
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout_3.addWidget(self.checkBox_4)
        self.label_J2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_J2.setFont(font)
        self.label_J2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_J2.setObjectName("label_J2")
        self.horizontalLayout_3.addWidget(self.label_J2)
        self.label_currentPrice2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_currentPrice2.setFont(font)
        self.label_currentPrice2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_currentPrice2.setObjectName("label_currentPrice2")
        self.horizontalLayout_3.addWidget(self.label_currentPrice2)
        self.label_buyPrice2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_buyPrice2.setFont(font)
        self.label_buyPrice2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_buyPrice2.setObjectName("label_buyPrice2")
        self.horizontalLayout_3.addWidget(self.label_buyPrice2)
        self.label_amount2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_amount2.setFont(font)
        self.label_amount2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_amount2.setObjectName("label_amount2")
        self.horizontalLayout_3.addWidget(self.label_amount2)
        self.label_today2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_today2.setFont(font)
        self.label_today2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_today2.setObjectName("label_today2")
        self.horizontalLayout_3.addWidget(self.label_today2)
        self.label_profit2 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_profit2.setFont(font)
        self.label_profit2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_profit2.setObjectName("label_profit2")
        self.horizontalLayout_3.addWidget(self.label_profit2)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 3)
        self.horizontalLayout_3.setStretch(2, 3)
        self.horizontalLayout_3.setStretch(3, 3)
        self.horizontalLayout_3.setStretch(4, 3)
        self.horizontalLayout_3.setStretch(5, 3)
        self.horizontalLayout_3.setStretch(6, 3)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(420, 410, 321, 71))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_totalBuyPrice = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_totalBuyPrice.setFont(font)
        self.label_totalBuyPrice.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_totalBuyPrice.setObjectName("label_totalBuyPrice")
        self.gridLayout_2.addWidget(self.label_totalBuyPrice, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 1, 0, 1, 1)
        self.label_totalProfit = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_totalProfit.setFont(font)
        self.label_totalProfit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_totalProfit.setObjectName("label_totalProfit")
        self.gridLayout_2.addWidget(self.label_totalProfit, 1, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 2)
        self.pushButton_remove = QtWidgets.QPushButton(self.tab)
        self.pushButton_remove.setGeometry(QtCore.QRect(310, 450, 89, 31))
        self.pushButton_remove.setObjectName("pushButton_remove")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(310, 410, 91, 31))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 410, 181, 72))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_14 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setWordWrap(True)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_4.addWidget(self.label_14)
        self.textEdit = QtWidgets.QTextEdit(self.horizontalLayoutWidget_4)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_4.addWidget(self.textEdit)
        self.horizontalLayout_4.setStretch(0, 2)
        self.horizontalLayout_4.setStretch(1, 1)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 140, 731, 41))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkBox_5 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_5.sizePolicy().hasHeightForWidth())
        self.checkBox_5.setSizePolicy(sizePolicy)
        self.checkBox_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_5.setText("")
        self.checkBox_5.setChecked(False)
        self.checkBox_5.setObjectName("checkBox_5")
        self.horizontalLayout_5.addWidget(self.checkBox_5)
        self.label_J3 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_J3.setFont(font)
        self.label_J3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_J3.setObjectName("label_J3")
        self.horizontalLayout_5.addWidget(self.label_J3)
        self.label_currentPrice3 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_currentPrice3.setFont(font)
        self.label_currentPrice3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_currentPrice3.setObjectName("label_currentPrice3")
        self.horizontalLayout_5.addWidget(self.label_currentPrice3)
        self.label_buyPrice3 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_buyPrice3.setFont(font)
        self.label_buyPrice3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_buyPrice3.setObjectName("label_buyPrice3")
        self.horizontalLayout_5.addWidget(self.label_buyPrice3)
        self.label_amount3 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_amount3.setFont(font)
        self.label_amount3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_amount3.setObjectName("label_amount3")
        self.horizontalLayout_5.addWidget(self.label_amount3)
        self.label_today3 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_today3.setFont(font)
        self.label_today3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_today3.setObjectName("label_today3")
        self.horizontalLayout_5.addWidget(self.label_today3)
        self.label_profit3 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_profit3.setFont(font)
        self.label_profit3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_profit3.setObjectName("label_profit3")
        self.horizontalLayout_5.addWidget(self.label_profit3)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 3)
        self.horizontalLayout_5.setStretch(2, 3)
        self.horizontalLayout_5.setStretch(3, 3)
        self.horizontalLayout_5.setStretch(4, 3)
        self.horizontalLayout_5.setStretch(5, 3)
        self.horizontalLayout_5.setStretch(6, 3)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(10, 180, 731, 41))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkBox_6 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_6.sizePolicy().hasHeightForWidth())
        self.checkBox_6.setSizePolicy(sizePolicy)
        self.checkBox_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_6.setText("")
        self.checkBox_6.setChecked(False)
        self.checkBox_6.setObjectName("checkBox_6")
        self.horizontalLayout_6.addWidget(self.checkBox_6)
        self.label_J4 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_J4.setFont(font)
        self.label_J4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_J4.setObjectName("label_J4")
        self.horizontalLayout_6.addWidget(self.label_J4)
        self.label_currentPrice4 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_currentPrice4.setFont(font)
        self.label_currentPrice4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_currentPrice4.setObjectName("label_currentPrice4")
        self.horizontalLayout_6.addWidget(self.label_currentPrice4)
        self.label_buyPrice4 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_buyPrice4.setFont(font)
        self.label_buyPrice4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_buyPrice4.setObjectName("label_buyPrice4")
        self.horizontalLayout_6.addWidget(self.label_buyPrice4)
        self.label_amount4 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_amount4.setFont(font)
        self.label_amount4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_amount4.setObjectName("label_amount4")
        self.horizontalLayout_6.addWidget(self.label_amount4)
        self.label_today4 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_today4.setFont(font)
        self.label_today4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_today4.setObjectName("label_today4")
        self.horizontalLayout_6.addWidget(self.label_today4)
        self.label_profit4 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_profit4.setFont(font)
        self.label_profit4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_profit4.setObjectName("label_profit4")
        self.horizontalLayout_6.addWidget(self.label_profit4)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 3)
        self.horizontalLayout_6.setStretch(2, 3)
        self.horizontalLayout_6.setStretch(3, 3)
        self.horizontalLayout_6.setStretch(4, 3)
        self.horizontalLayout_6.setStretch(5, 3)
        self.horizontalLayout_6.setStretch(6, 3)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(10, 220, 731, 41))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.checkBox_7 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_7.sizePolicy().hasHeightForWidth())
        self.checkBox_7.setSizePolicy(sizePolicy)
        self.checkBox_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_7.setText("")
        self.checkBox_7.setChecked(False)
        self.checkBox_7.setObjectName("checkBox_7")
        self.horizontalLayout_7.addWidget(self.checkBox_7)
        self.label_J5 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_J5.setFont(font)
        self.label_J5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_J5.setObjectName("label_J5")
        self.horizontalLayout_7.addWidget(self.label_J5)
        self.label_currentPrice5 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_currentPrice5.setFont(font)
        self.label_currentPrice5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_currentPrice5.setObjectName("label_currentPrice5")
        self.horizontalLayout_7.addWidget(self.label_currentPrice5)
        self.label_buyPrice5 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_buyPrice5.setFont(font)
        self.label_buyPrice5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_buyPrice5.setObjectName("label_buyPrice5")
        self.horizontalLayout_7.addWidget(self.label_buyPrice5)
        self.label_amount5 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_amount5.setFont(font)
        self.label_amount5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_amount5.setObjectName("label_amount5")
        self.horizontalLayout_7.addWidget(self.label_amount5)
        self.label_today5 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_today5.setFont(font)
        self.label_today5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_today5.setObjectName("label_today5")
        self.horizontalLayout_7.addWidget(self.label_today5)
        self.label_profit5 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_profit5.setFont(font)
        self.label_profit5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_profit5.setObjectName("label_profit5")
        self.horizontalLayout_7.addWidget(self.label_profit5)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 3)
        self.horizontalLayout_7.setStretch(2, 3)
        self.horizontalLayout_7.setStretch(3, 3)
        self.horizontalLayout_7.setStretch(4, 3)
        self.horizontalLayout_7.setStretch(5, 3)
        self.horizontalLayout_7.setStretch(6, 3)
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(10, 260, 731, 41))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.checkBox_8 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_8.sizePolicy().hasHeightForWidth())
        self.checkBox_8.setSizePolicy(sizePolicy)
        self.checkBox_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_8.setText("")
        self.checkBox_8.setChecked(False)
        self.checkBox_8.setObjectName("checkBox_8")
        self.horizontalLayout_8.addWidget(self.checkBox_8)
        self.label_J6 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_J6.setFont(font)
        self.label_J6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_J6.setObjectName("label_J6")
        self.horizontalLayout_8.addWidget(self.label_J6)
        self.label_currentPrice6 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_currentPrice6.setFont(font)
        self.label_currentPrice6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_currentPrice6.setObjectName("label_currentPrice6")
        self.horizontalLayout_8.addWidget(self.label_currentPrice6)
        self.label_buyPrice6 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_buyPrice6.setFont(font)
        self.label_buyPrice6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_buyPrice6.setObjectName("label_buyPrice6")
        self.horizontalLayout_8.addWidget(self.label_buyPrice6)
        self.label_amount6 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_amount6.setFont(font)
        self.label_amount6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_amount6.setObjectName("label_amount6")
        self.horizontalLayout_8.addWidget(self.label_amount6)
        self.label_today6 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_today6.setFont(font)
        self.label_today6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_today6.setObjectName("label_today6")
        self.horizontalLayout_8.addWidget(self.label_today6)
        self.label_profit6 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_profit6.setFont(font)
        self.label_profit6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_profit6.setObjectName("label_profit6")
        self.horizontalLayout_8.addWidget(self.label_profit6)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 3)
        self.horizontalLayout_8.setStretch(2, 3)
        self.horizontalLayout_8.setStretch(3, 3)
        self.horizontalLayout_8.setStretch(4, 3)
        self.horizontalLayout_8.setStretch(5, 3)
        self.horizontalLayout_8.setStretch(6, 3)
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(10, 300, 731, 41))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_9.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.checkBox_9 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_9.sizePolicy().hasHeightForWidth())
        self.checkBox_9.setSizePolicy(sizePolicy)
        self.checkBox_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_9.setText("")
        self.checkBox_9.setChecked(False)
        self.checkBox_9.setObjectName("checkBox_9")
        self.horizontalLayout_9.addWidget(self.checkBox_9)
        self.label_J7 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_J7.setFont(font)
        self.label_J7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_J7.setObjectName("label_J7")
        self.horizontalLayout_9.addWidget(self.label_J7)
        self.label_currentPrice7 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_currentPrice7.setFont(font)
        self.label_currentPrice7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_currentPrice7.setObjectName("label_currentPrice7")
        self.horizontalLayout_9.addWidget(self.label_currentPrice7)
        self.label_buyPrice7 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_buyPrice7.setFont(font)
        self.label_buyPrice7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_buyPrice7.setObjectName("label_buyPrice7")
        self.horizontalLayout_9.addWidget(self.label_buyPrice7)
        self.label_amount7 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_amount7.setFont(font)
        self.label_amount7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_amount7.setObjectName("label_amount7")
        self.horizontalLayout_9.addWidget(self.label_amount7)
        self.label_today7 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_today7.setFont(font)
        self.label_today7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_today7.setObjectName("label_today7")
        self.horizontalLayout_9.addWidget(self.label_today7)
        self.label_profit7 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_profit7.setFont(font)
        self.label_profit7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_profit7.setObjectName("label_profit7")
        self.horizontalLayout_9.addWidget(self.label_profit7)
        self.horizontalLayout_9.setStretch(0, 1)
        self.horizontalLayout_9.setStretch(1, 3)
        self.horizontalLayout_9.setStretch(2, 3)
        self.horizontalLayout_9.setStretch(3, 3)
        self.horizontalLayout_9.setStretch(4, 3)
        self.horizontalLayout_9.setStretch(5, 3)
        self.horizontalLayout_9.setStretch(6, 3)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(9, 349, 731, 61))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 1, 1, 1)
        self.textEdit_name = QtWidgets.QTextEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_name.sizePolicy().hasHeightForWidth())
        self.textEdit_name.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.textEdit_name.setFont(font)
        self.textEdit_name.setObjectName("textEdit_name")
        self.gridLayout_3.addWidget(self.textEdit_name, 1, 0, 1, 1)
        self.textEdit_buyP = QtWidgets.QTextEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_buyP.sizePolicy().hasHeightForWidth())
        self.textEdit_buyP.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.textEdit_buyP.setFont(font)
        self.textEdit_buyP.setObjectName("textEdit_buyP")
        self.gridLayout_3.addWidget(self.textEdit_buyP, 1, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.textEdit_amount = QtWidgets.QTextEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_amount.sizePolicy().hasHeightForWidth())
        self.textEdit_amount.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.textEdit_amount.setFont(font)
        self.textEdit_amount.setObjectName("textEdit_amount")
        self.gridLayout_3.addWidget(self.textEdit_amount, 1, 3, 1, 1)
        self.textEdit_code = QtWidgets.QTextEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_code.sizePolicy().hasHeightForWidth())
        self.textEdit_code.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.textEdit_code.setFont(font)
        self.textEdit_code.setObjectName("textEdit_code")
        self.gridLayout_3.addWidget(self.textEdit_code, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 3, 1, 1)
        self.pushButton_add = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_add.sizePolicy().hasHeightForWidth())
        self.pushButton_add.setSizePolicy(sizePolicy)
        self.pushButton_add.setObjectName("pushButton_add")
        self.gridLayout_3.addWidget(self.pushButton_add, 1, 4, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 773, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.pushButton.clicked.connect(self.slot_refresh)
        self.pushButton_remove.clicked.connect(self.slot_remove)
        self.pushButton_add.clicked.connect(self.slot_add)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_6.setText(_translate("MainWindow", "Profit"))
        self.label_4.setText(_translate("MainWindow", "AMOUNT"))
        self.label_2.setText(_translate("MainWindow", "Current Price"))
        self.label.setText(_translate("MainWindow", "Name / Code"))
        self.label_3.setText(_translate("MainWindow", "Buy Price"))
        self.label_5.setText(_translate("MainWindow", "Buy Date"))
        self.label_J1.setText(_translate("MainWindow", "NE"))
        self.label_currentPrice1.setText(_translate("MainWindow", "TextLabel"))
        self.label_buyPrice1.setText(_translate("MainWindow", "TextLabel"))
        self.label_amount1.setText(_translate("MainWindow", "TextLabel"))
        self.label_today1.setText(_translate("MainWindow", "TextLabel"))
        self.label_profit1.setText(_translate("MainWindow", "TextLabel"))
        self.label_J2.setText(_translate("MainWindow", "TextLabel"))
        self.label_currentPrice2.setText(_translate("MainWindow", "TextLabel"))
        self.label_buyPrice2.setText(_translate("MainWindow", "TextLabel"))
        self.label_amount2.setText(_translate("MainWindow", "TextLabel"))
        self.label_today2.setText(_translate("MainWindow", "TextLabel"))
        self.label_profit2.setText(_translate("MainWindow", "TextLabel"))
        self.label_13.setText(_translate("MainWindow", "Total Buy Price"))
        self.label_totalBuyPrice.setText(_translate("MainWindow", "TextLabel"))
        self.label_15.setText(_translate("MainWindow", "Totsl Profit"))
        self.label_totalProfit.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_remove.setText(_translate("MainWindow", "Remove"))
        self.pushButton.setText(_translate("MainWindow", "Refresh"))
        self.label_14.setText(_translate("MainWindow", "Refresh Time(s)"))
        self.label_J3.setText(_translate("MainWindow", "TextLabel"))
        self.label_currentPrice3.setText(_translate("MainWindow", "TextLabel"))
        self.label_buyPrice3.setText(_translate("MainWindow", "TextLabel"))
        self.label_amount3.setText(_translate("MainWindow", "TextLabel"))
        self.label_today3.setText(_translate("MainWindow", "TextLabel"))
        self.label_profit3.setText(_translate("MainWindow", "TextLabel"))
        self.label_J4.setText(_translate("MainWindow", "TextLabel"))
        self.label_currentPrice4.setText(_translate("MainWindow", "TextLabel"))
        self.label_buyPrice4.setText(_translate("MainWindow", "TextLabel"))
        self.label_amount4.setText(_translate("MainWindow", "TextLabel"))
        self.label_today4.setText(_translate("MainWindow", "TextLabel"))
        self.label_profit4.setText(_translate("MainWindow", "TextLabel"))
        self.label_J5.setText(_translate("MainWindow", "TextLabel"))
        self.label_currentPrice5.setText(_translate("MainWindow", "TextLabel"))
        self.label_buyPrice5.setText(_translate("MainWindow", "TextLabel"))
        self.label_amount5.setText(_translate("MainWindow", "TextLabel"))
        self.label_today5.setText(_translate("MainWindow", "TextLabel"))
        self.label_profit5.setText(_translate("MainWindow", "TextLabel"))
        self.label_J6.setText(_translate("MainWindow", "TextLabel"))
        self.label_currentPrice6.setText(_translate("MainWindow", "TextLabel"))
        self.label_buyPrice6.setText(_translate("MainWindow", "TextLabel"))
        self.label_amount6.setText(_translate("MainWindow", "TextLabel"))
        self.label_today6.setText(_translate("MainWindow", "TextLabel"))
        self.label_profit6.setText(_translate("MainWindow", "TextLabel"))
        self.label_J7.setText(_translate("MainWindow", "TextLabel"))
        self.label_currentPrice7.setText(_translate("MainWindow", "TextLabel"))
        self.label_buyPrice7.setText(_translate("MainWindow", "TextLabel"))
        self.label_amount7.setText(_translate("MainWindow", "TextLabel"))
        self.label_today7.setText(_translate("MainWindow", "TextLabel"))
        self.label_profit7.setText(_translate("MainWindow", "TextLabel"))
        self.label_8.setText(_translate("MainWindow", "Code"))
        self.label_7.setText(_translate("MainWindow", "Name"))
        self.label_9.setText(_translate("MainWindow", "BuyPrice"))
        self.label_10.setText(_translate("MainWindow", "Amount"))
        self.pushButton_add.setText(_translate("MainWindow", "Add"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Search"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Trade"))



    def getMaxLength(self) :
        return MAX_LENGTH
    
    def sendInfoClsInst(self, cls) :
        self.infoCls = cls

    def do_refresh(self) :
        self.infoCls.refresh(self)
        
    def updateName(self, index, text) :
        if index == 0 :
            self.label_J1.setText(text)
        elif index == 1 :
            self.label_J2.setText(text)
        elif index == 2 :
            self.label_J3.setText(text)
        elif index == 3 :
            self.label_J4.setText(text)
        elif index == 4 :
            self.label_J5.setText(text)
        elif index == 5 :
            self.label_J6.setText(text)
        elif index == 6 :
            self.label_J7.setText(text)

    def updateCurrentPrice(self, index, price) :
        if index == 0 :
            self.label_currentPrice1.setText(price)
        elif index == 1 :
            self.label_currentPrice2.setText(price)
        elif index == 2 :
            self.label_currentPrice3.setText(price)
        elif index == 3 :
            self.label_currentPrice4.setText(price)
        elif index == 4 :
            self.label_currentPrice5.setText(price)
        elif index == 5 :
            self.label_currentPrice6.setText(price)
        elif index == 6 :
            self.label_currentPrice7.setText(price)

    def updateBuyPrice(self, index, price) :
        if index == 0 :
            self.label_buyPrice1.setText(price)
        elif index == 1 :
            self.label_buyPrice2.setText(price)
        elif index == 2 :
            self.label_buyPrice3.setText(price)
        elif index == 3 :
            self.label_buyPrice4.setText(price)
        elif index == 4 :
            self.label_buyPrice5.setText(price)
        elif index == 5 :
            self.label_buyPrice6.setText(price)
        elif index == 6 :
            self.label_buyPrice7.setText(price)
            
    def updateAmount(self, index, amount) :
        if index == 0 :
            self.label_amount1.setText(amount)
        elif index == 1 :
            self.label_amount2.setText(amount)
        elif index == 2 :
            self.label_amount3.setText(amount)
        elif index == 3 :
            self.label_amount4.setText(amount)
        elif index == 4 :
            self.label_amount5.setText(amount)
        elif index == 5 :
            self.label_amount6.setText(amount)
        elif index == 6 :
            self.label_amount7.setText(amount)
            
    def updateToday(self, index, today) :
        if index == 0 :
            self.label_today1.setText(today)
        elif index == 1 :
            self.label_today2.setText(today)
        elif index == 2 :
            self.label_today3.setText(today)
        elif index == 3 :
            self.label_today4.setText(today)
        elif index == 4 :
            self.label_today5.setText(today)
        elif index == 5 :
            self.label_today6.setText(today)
        elif index == 6 :
            self.label_today7.setText(today)

    def updateProfit(self, index, profit, fontcolor) :
        if index == 0 :
            self.label_profit1.setText(profit)
            self.label_profit1.setStyleSheet('QLabel#label_profit1 {color: %s}'%fontcolor)
        elif index == 1 :
            self.label_profit2.setText(profit)
            self.label_profit2.setStyleSheet('QLabel#label_profit2 {color: %s}'%fontcolor)
        elif index == 2 :
            self.label_profit3.setText(profit)
            self.label_profit3.setStyleSheet('QLabel#label_profit3 {color: %s}'%fontcolor)
        elif index == 3 :
            self.label_profit4.setText(profit)
            self.label_profit4.setStyleSheet('QLabel#label_profit4 {color: %s}'%fontcolor)
        elif index == 4 :
            self.label_profit5.setText(profit)
            self.label_profit5.setStyleSheet('QLabel#label_profit5 {color: %s}'%fontcolor)
        elif index == 5 :
            self.label_profit6.setText(profit)
            self.label_profit6.setStyleSheet('QLabel#label_profit6 {color: %s}'%fontcolor)
        elif index == 6 :
            self.label_profit7.setText(profit)
            self.label_profit7.setStyleSheet('QLabel#label_profit7 {color: %s}'%fontcolor)

    def updateTotalBuyPrice(self, price) :
        self.label_totalBuyPrice.setText(price)

    def updateTotalProfit(self, profit, fontcolor) :
        self.label_totalProfit.setText(profit)
        self.label_totalProfit.setStyleSheet('QLabel#label_totalProfit {color: %s}'%fontcolor)

    def slot_add(self) :
        print("push add")
        print("name = " + self.textEdit_name.toPlainText()).strip()
        print("buyP = " + self.textEdit_buyP.toPlainText()).strip()
        print("amount=" + self.textEdit_amount.toPlainText()).strip()
        self.infoCls.saveIni(self.textEdit_name.toPlainText().strip(),\
                             self.textEdit_code.toPlainText().strip(),\
                             self.textEdit_buyP.toPlainText().strip(),\
                             self.textEdit_amount.toPlainText().strip())

        self.infoCls.loadIni()
        
    def slot_refresh(self) :
        print("push refresh")        
        self.do_refresh()

    def slot_remove(self) :
        print("push remove")

# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())

